import os

# Azure Storage
AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
AZURE_STORAGE_CONTAINER_NAME = "cafeteria"

# Azure OpenAI
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")
AZURE_OPENAI_MODEL = "gpt-4o"  # 또는 gpt-35-turbo
AZURE_OPENAI_API_VERSION = "2024-12-01-preview" 

# 기타 설정
PAST_DATA_FILENAME = "past_data.csv"
FUTURE_DATA_FILENAME = "future_data.csv"
WEATHER_DATA_FILENAME = "future_weather.csv"